cache:
  directories:
  - "$HOME/.m2"
services:
  - docker
language: java
dist: trusty
jdk:
  - oraclejdk8
before_install:
 - chmod +x mvnw
 # install heroku CLI
 - wget -qO- https://toolbelt.heroku.com/install.sh | sh
 - echo $HEROKU_PASSWORD | docker login -u $HEROKU_USERNAME --password-stdin registry.heroku.com
script: mvn clean verify
 - docker build -t antarctica-lab .
deploy:
 provider: script
 script:
   docker push registry.heroku.com/$HEROKU_APP_NAME/web;
   heroku container:release web --app $HEROKU_APP_NAME
 on:
   branch: master
notifications:
  email:
    - ht.housseine@gmail.com