cache:
  directories:
  - "$HOME/.m2"
services:
  - docker
language: java
dist: trusty
jdk:
  - oraclejdk8
sudo: required
before_install:
 - chmod +x mvnw
 # install heroku CLI
 - wget -qO- https://toolbelt.heroku.com/install.sh | sh
 - whereis heroku
 - docker login --username="housseine2014tassa@gamil.com" --password=$HEROKU_API_KEY registry.heroku.com

script: 
 - mvn clean verify
 - docker build -f antarctica-lab/Dockerfile -t antarctica-lab .
 - docker tag antarctica-lab registry.heroku.com/$HEROKU_APP_NAME/web;
 - docker build -f clothes/Dockerfile -t niollo-clothes-api .
 - docker tag niollo-clothes-api registry.heroku.com/niollo-clothes-api/web;
 
deploy:
 provider: script
 script:
   docker push registry.heroku.com/$HEROKU_APP_NAME/web;
   heroku container:release web --app $HEROKU_APP_NAME
   docker push registry.heroku.com/niollo-clothes-api/web;
   heroku container:release web --app niollo-clothes-api
 on:
   branch: master
notifications:
  email:
    - ht.housseine@gmail.com